### ISSUE TITLE
七牛云的几个参数错误

### ISSUE THREAD

**Issue by hulang** [yzh52521/think-filesystem#1]
驱动下：Qiniu.php
use Overtrue\Flysystem\QiNiu\QiniuAdapter;

QiNiu  中的N是小写

use Overtrue\Flysystem\Qiniu\QiniuAdapter;

参数错误：access_key，secret_key，domain
        return new QiniuAdapter(
            $this->config['access_key'], $this->config['secret_key'],
            $this->config['bucket'], $this->config['domain']
        );

应该是：accessKey，secretKey，url
        return new QiniuAdapter(
            $this->config['accessKey'], $this->config['secretKey'],
            $this->config['bucket'], $this->config['url']
        );

改好了。但是还是报错，使用的是：
catch (\think\exception\ValidateException $e) {

$e->getMessage()

错误
Trying to get property 'srcUpHosts' of non-object

**Comment by yuanzhihai** [comment]
我也没有账号 没法测试

**Comment by hulang** [comment]
@yzh52521 bucket我写错了。你上面的那几个错误参数改下，推送下版本。。我更新

**Comment by yuanzhihai** [comment]
> @yzh52521 bucket我写错了。你上面的那几个错误参数改下，推送下版本。。我更新

发布了 你测试下
