### ISSUE TITLE
TP8.0安装冲突

### ISSUE THREAD

**Issue by xbai8** [yzh52521/think-filesystem#11]
这个不能安装在TP的8.0里面吗？在8.0里面安装提示版本冲突
![image](https://github.com/yuanzhihai/think-filesystem/assets/88012952/9e87db0b-1ceb-4e56-9150-ff84e1bd088d)

**Comment by yuanzhihai** [comment]
可以安装啊，你是不是默认安装了tp的了？

**Comment by xbai8** [comment]
是的，我主框架就是TP8.0，在TP8内安装的你这个报的这个问题

**Comment by yuanzhihai** [comment]
> 是的，我主框架就是TP8.0，在TP8内安装的你这个报的这个问题

卸载 tp 的 think-filesystem 他用的是  league/flysystem 2.0  php8要用 3.0

**Comment by xbai8** [comment]
现在卸载了TP的think-filesystem，安装你这里面的，附带了think-filesystem3.0了，下次安装了，他会优先安装你这个3.0还是TP得呀？  我怕到时候冲突

**Comment by xbai8** [comment]
已经搞定了，感谢
