### ISSUE TITLE
请问一下-如何动态传入配置进行上传呢？

### ISSUE THREAD

**Issue by xbai8** [yzh52521/think-filesystem#12]
![image](https://github.com/yuanzhihai/think-filesystem/assets/88012952/993a734f-25fb-4e66-9423-afba47d4024b)

你好，请问一下，如图中，想动态传入配置项进行上传，该如何写呢，我这边看了TP的文档好像也没有
但我的配置项是存在数据库中的，并没有直接写在config目录的filesystem.php

**Comment by yuanzhihai** [comment]
> ![image](https://user-images.githubusercontent.com/88012952/267278296-993a734f-25fb-4e66-9423-afba47d4024b.png)
> 
> 你好，请问一下，如图中，想动态传入配置项进行上传，该如何写呢，我这边看了TP的文档好像也没有 但我的配置项是存在数据库中的，并没有直接写在config目录的filesystem.php
第一个参数是 cache

**Comment by xbai8** [comment]
![image](https://github.com/yuanzhihai/think-filesystem/assets/88012952/9d869248-65c7-4538-8f3d-358f97347b5f)
这个好像传入了就会报错

**Comment by yuanzhihai** [comment]
```
 public function upload(\think\Cache $cache){

}
```

**Comment by xbai8** [comment]
![image](https://github.com/yuanzhihai/think-filesystem/assets/88012952/29b63507-808f-4fc2-97f6-bf08576e3e3b)
似乎一样的

**Comment by yuanzhihai** [comment]
这个是抽象类

**Comment by yuanzhihai** [comment]
为什么要这么用呢？

**Comment by xbai8** [comment]
方便加QQ吗？958416459

**Comment by yuanzhihai** [comment]
你加我吧 396751927
