### ISSUE TITLE
Sftp上传，为什么总是上传到的是本地呢？

### ISSUE THREAD

**Issue by hulang** [yzh52521/think-filesystem#2]
1、到底怎么配置，可以上传到服务器上面去，我win10+Laragon6.0.0  PHP7.4环境，总是上传到本地

2、返回的图片，带指定URL

比如：aliyun，qiniu，都有个URL参数。。

如指定URL设置为：https://www.baidu.com
上传后的图片是：/image/20221029/4a77ff79005a44d8a74bb4b3bae3c37b.png
应该是：https://www.baidu.com/image/20221029/4a77ff79005a44d8a74bb4b3bae3c37b.png

sftp配置里面，目前其它都是对的。root设置为：/home/wwwroot/xxxxx
上传到的是本地在D盘新建/home/wwwroot/xxxxx。。。反正无法上传到服务器。我用League\Flysystem\Sftp单独上传可以上传到服务器上面。

**Comment by yuanzhihai** [comment]
用League\Flysystem\Sftp单独上传可以上传到服务器上面。 代码怎么写的？

**Comment by hulang** [comment]
@yzh52521 这样上传成功。


    public function index()
    {
        $config = [];
        $config['host'] = '192.1.197.82';
        $config['username'] = 'root';
        $config['password'] = '1231313';
        $config['privateKey'] = null;
        $config['passphrase'] = null;
        $config['port'] = 22;
        $config['useAgent'] = false;
        $config['timeout'] = 30;
        $config['maxTries'] = 4;
        $config['hostFingerprint'] = null;
        $config['connectivityChecker'] = null;
        $connectionProvider = SftpConnectionProvider::fromArray($config);
        $adapter = new SftpAdapter(
            $connectionProvider,
            '/home/wwwroot/apic',
            PortableVisibilityConverter::fromArray([
                'file' => [
                    'public' => 0755,
                    'private' => 0755,
                ],
                'dir' => [
                    'public' => 0755,
                    'private' => 0755,
                ],
            ])
        );
        $filesystem = new Filesystem($adapter);
        // 文件名称
        $fileName = 'readme.md';
        // 本地文件位置
        $file = getStaticPath() . $fileName;
        // 读取文件
        $info = File::read_file($file);
        $success = '';
        // 上传文件
        try {
            $filesystem->write($fileName, $info);
            $success = 'ok';
        } catch (FilesystemException $exception) {
            $success = 'failed';
        }
        $json = [];
        $json['file'] = $file;
        $json['info'] = $info;
        $json['success'] = $success;
        return json_encode($json);
    }

**Comment by yuanzhihai** [comment]
我测试的代码 
配置：
```
'sftp'   => [
            'type'       => 'sftp',
            'host'       => '',
            'port'       => 22,
            'username'   => '',
            'password'   => '',
            'privateKey' => null,
            'passphrase' => null,
            'root'       => '/home/wwwroot/order',
            'url'        => '/home/wwwroot/order',
            'timeout'    => 30,
        ]
```

代码：
```

        try {
            validate(
                [
                    'image' => [
                        // 限制文件大小(单位b)，这里限制为4M
                        'fileSize' => 10 * 1024 * 1000,
                        // 限制文件后缀，多个后缀以英文逗号分割
                        'fileExt'  => 'gif,jpg,png,jpeg'
                    ]
                ]
            )->check( ['image' => $file] );


            $filename = date( 'Ymd' ).DIRECTORY_SEPARATOR.$file->hash().'.'.$file->extension();

            $path = \yzh52521\filesystem\facade\Filesystem::disk( 'sftp' )->putFileAs( 'test',$file,$filename );

            $url = \yzh52521\filesystem\facade\Filesystem::disk( 'sftp' )->url( $path );

            $info = [
                'path' => $path,
                'url'  => $url,
            ];
            return json( $info );
        } catch ( \think\exception\ValidateException $e ) {
            echo $e->getMessage();
        } catch ( \TypeError $e ) {
            echo '未上传';
        }
```

**Comment by hulang** [comment]
@yzh52521 更新到v2.0.4   Sftp上传可以了，但是七牛云的，看你把url改成了domain。 
我也把配置里面七牛云的url改成了domain。。。我在：Qiniu.php驱动中也打印了。是设置对的..
但是上传后不带domain设置的域名了。。
我再七牛云的网站上看了。有图片。上传了。。我也清理了runtime目录。。上传后，还是不带域名。。。
好郁闷啊。。。。。到底哪里错误了呢。。。奇怪了。

**Comment by yuanzhihai** [comment]
> @yzh52521 更新到v2.0.4 Sftp上传可以了，但是七牛云的，看你把url改成了domain。 我也把配置里面七牛云的url改成了domain。。。我在：Qiniu.php驱动中也打印了。是设置对的.. 但是上传后不带domain设置的域名了。。 我再七牛云的网站上看了。有图片。上传了。。我也清理了runtime目录。。上传后，还是不带域名。。。 好郁闷啊。。。。。到底哪里错误了呢。。。奇怪了。

怎么获取的？

$url = \yzh52521\filesystem\facade\Filesystem::disk( 'qiniu' )->url( $path ); 这样么？

**Comment by hulang** [comment]
@yzh52521 
$path = \yzh52521\filesystem\facade\Filesystem::disk($driver)->putFile($dir, $file);
                $path = str_replace('\\', '/', $path);
                // 拼接URL路径
                $url = \yzh52521\filesystem\facade\Filesystem::getDiskConfig($driver, 'url') . '/' . $path;

这样玩的。。我就把前面的think换成你写的。。

**Comment by yuanzhihai** [comment]
> @yzh52521 $path = \yzh52521\filesystem\facade\Filesystem::disk($driver)->putFile($dir, $file); $path = str_replace('\', '/', $path); // 拼接URL路径 $url = \yzh52521\filesystem\facade\Filesystem::getDiskConfig($driver, 'url') . '/' . $path;
> 
> 这样玩的。。我就把前面的think换成你写的。。

这样获取不到 ，用 $url = \yzh52521\filesystem\facade\Filesystem::disk( 'qiniu' )->url( $path ); 这个

 public 和 sftp   才使用配置的url

**Comment by yuanzhihai** [comment]
使用文件地址 用 url 方法

**Comment by yuanzhihai** [comment]
你可以看下 Driver 类 我加了很多功能，大概用法和laravel一样

**Comment by hulang** [comment]
> 你可以看下 Driver 类 我加了很多功能，大概用法和laravel一样
2.0.3我那样可以获取到。
我的驱动，是动态的啊。。用的变量：$driver。。。。你说：public 和 sftp 才使用配置的url.......。。。哎，都糊涂了。

PS：你用的开发编辑器好像也是vs code，怎么不格式下：php代码啊。。。。有的代码看着好难受。。。

**Comment by hulang** [comment]
> 你可以看下 Driver 类 我加了很多功能，大概用法和laravel一样

加了很多功能。好多方法都是英文的，格式化下代码啊。。

**Comment by hulang** [comment]
@yzh52521 可以了。。
`$url = \yzh52521\filesystem\facade\Filesystem::disk($driver)->url($path);`
