### ISSUE TITLE
华为云如何配置？上传不成功，报错：Argument #1 ($option) must be of type array

### ISSUE THREAD

**Issue by bmkj** [yzh52521/think-filesystem#4]
报错如下：
yzh52521\Flysystem\Obs\ObsAdapter::__construct(): Argument #1 ($option) must be of type array, Obs\ObsClient given, called in D:\wwwroot\abc.com\vendor\yzh52521\think-filesystem\src\driver\Obs.php on line 29

**Comment by yuanzhihai** [comment]
你怎么配置的？ 我没有账户 还没有测试过，你调试一下看看  如果代码有问题欢迎 提交pr

**Comment by bmkj** [comment]
华为云这2个配置，我都填false，上面的配置就是华为云的正常配置：
'ssl_verify' => false,
 'debug'      => false,
报错说$option必须为数组

**Comment by yuanzhihai** [comment]
没有 option 这个参数   你自己调试一下
