### ISSUE TITLE
老大，修改为适配php7.4+的版本，让更多人用

### ISSUE THREAD

**Issue by bmkj** [yzh52521/think-filesystem#7]
老大，修改为适配php7.4+的版本，让更多人用
另外，你自己测试下华为云存储，我配置后不成功，报错信息在另一个帖子有说明

**Comment by yuanzhihai** [comment]
7.4 用 v2版本
8.0 用v3

**Comment by bmkj** [comment]
v2版本是这个吗？https://github.com/yzh52521/thinkphp-filesystem-cloud

**Comment by yuanzhihai** [comment]
composer require yzh52521/think-filesystem  ^2.0
