### ISSUE TITLE
报错：Call to a member function hashName() on null

### ISSUE THREAD

**Issue by bmkj** [yzh52521/think-filesystem#8]
#0 [0]Error in Driver.php line 551
Call to a member function hashName() on null
    
    public function putFile(string $path,$file,$rule = null,array $options = [])
    {
        $file = is_string( $file ) ? new File( $file ) : $file;
//下面这一行报错：
        return $this->putFileAs( $path,$file,$file->hashName( $rule ),$options );
    }

**Comment by yuanzhihai** [comment]
你用的 那个版本？
完整代码发我一下 我看看

**Comment by bmkj** [comment]
tp6.1+你的2.0版本，PHP7.4

**Comment by yuanzhihai** [comment]
> tp6.1+你的2.0版本，PHP7.4

我自己也用了 没问题啊，你使用的那个驱动上传的 ？你发下你使用的代码

**Comment by bmkj** [comment]
就是你提供的示例代码^ ^：
if(request()->isPost()){
            $file = request()->file( 'image' );
              try {
                    validate(
                        ['image' => [
                                // 限制文件大小(单位b)，这里限制为4M
                                'fileSize' => 10 * 1024 * 1000,
                                // 限制文件后缀，多个后缀以英文逗号分割
                                'fileExt'  => 'gif,jpg,png,jpeg'
                            ]
                        ])->check( ['image' => $file] );

                    $path     = \yzh52521\filesystem\facade\Filesystem::disk( 'qiniu' )->putFile( 'test',$file);
                    $url      = \yzh52521\filesystem\facade\Filesystem::disk( 'qiniu' )->url( $path );
                    return json( ['path' => $path,'url'  => $url] );
              } catch ( \think\exception\ValidateException $e ) {
                    echo $e->getMessage();
             }
        }else{
            return view();
        }

**Comment by bmkj** [comment]
环境是：tp6.1+你的2.0版本+PHP7.4

**Comment by yuanzhihai** [comment]
你试试 本地 可以上传么

**Comment by yuanzhihai** [comment]
qiniu 的我也没有账户 没法测试

**Comment by yuanzhihai** [comment]
阿里云的我测试没有问题

**Comment by bmkj** [comment]
测试七牛云，阿里云，腾讯云，本地都OK了，
但是七牛云的配置文件，这2个参数access_key、secret_key分别改为：accessKey、secretKey即可。
环境是：windows+apache+tp6.1+你的2.0版本+PHP7.4/8.0
但是在PHP8.1下报错（能兼容PHP8.1吗？）：
#0 [1]ErrorException in Config.php line 9
During inheritance of ArrayAccess: Uncaught think\exception\ErrorException: Return type of Overtrue\CosClient\Config::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\wwwroot\tp.com\vendor\overtrue\qcloud-cos-client\src\Config.php:92
Stack trace:

**Comment by bmkj** [comment]
PHP8.1腾讯云报错，阿里云和七牛云，本地都OK，就是你的2.0版本

**Comment by yuanzhihai** [comment]
> 测试七牛云，阿里云，腾讯云，本地都OK了， 但是七牛云的配置文件，这2个参数access_key、secret_key分别改为：accessKey、secretKey即可。 环境是：windows+apache+tp6.1+你的2.0版本+PHP7.4/8.0 但是在PHP8.1下报错（能兼容PHP8.1吗？）： #0 [1]ErrorException in Config.php line 9 During inheritance of ArrayAccess: Uncaught think\exception\ErrorException: Return type of Overtrue\CosClient\Config::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in D:\wwwroot\tp.com\vendor\overtrue\qcloud-cos-client\src\Config.php:92 Stack trace:

我 v2文档 就是

'qiniu'  => [
    'type'      => 'qiniu',
    'accessKey' => '******',
    'secretKey' => '******',
    'bucket'    => 'bucket',
    'domain'       => '',
],
大写好不

**Comment by yuanzhihai** [comment]
> PHP8.1腾讯云报错，阿里云和七牛云，本地都OK，就是你的2.0版本

php8.1 你试试 3.0吧  
腾讯云报错要找 overtrue/flysystem-cos 这个包看看
